CREATE TABLE [User]
(
DODID INT
, [UIC] VARCHAR(10)
, [Command Name] VARCHAR(80)  
, [AO] BIT 
, [EMAIL] VARCHAR (80)
, [PHONE] VARCHAR(12)
, [Rank] VARCHAR (10)
, [First Name] VARCHAR (80)
, [Middle Name] VARCHAR(3)
, [Last Name] VARCHAR (80),
PRIMARY KEY CLUSTERED (DODID ASC),
CONSTRAINT [FK_USER_REQUEST_UIC] FOREIGN KEY (UIC)
REFERENCES [REQUEST](UIC) ON DELETE CASCADE
)